from typing import Literal

DifficultyLevel = Literal["easy", "medium", "hard"]

PROMPTS = {
    "easy": [
        "cat",
        "dog", 
        "elephant",
        "giraffe",
        "lion",
        "monkey",
        "penguin",
        "rabbit",
        "turtle",
        "bed",
        "door",
        "fan",
        "apple",
        "banana",
        "cake",
        "cookie",
        "car",
        "boat",
        "bus",
    ],
    "medium": [
        "airplane",
        "helicopter",
        "rocket",
        "castle",
        "bridge",
        "lighthouse", 
        "windmill",
        "doctor",
        "chef",
        "pilot",
        "dancer",
        "baseball",
        "basketball",
        "soccer",
        "tennis",
        "robot",
        "dragon",
        "wizard",
        "pirate",
        "ghost",
    ],
    "hard": [
        "thunderstorm",
        "northern lights", 
        "coral reef",
        "redwood forest",
        "hot air balloon",
        "vacuum cleaner",
        "musical conductor",
        "construction site",
        "garden party",
        "tug of war",
        "arm wrestling",
        "rock climbing",
        "thumb wrestling",
        "playing chess",
        "building sandcastle",
    ]
}
